package calculator_app;
/**
* CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Saturday, 9 May, 2026 1:24:19 PM IST
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculatorHelper.type ();
  }

}
