package calculator_app;
/**
* CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Saturday, 9 May, 2026 1:24:19 PM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int subtract (int a, int b);
  int multiply (int a, int b);
  float divide (float a, float b);
} // interface CalculatorOperations
